### ISSUE TITLE
 colors and Button Style Guild

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#104]
shula

**Comment by shulammiteofua** [comment]
[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/Buttons.png](url)
[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/Colors.png](url)
Colors and buttons used in the Bytsfy project
