### ISSUE TITLE
Documentation Pages

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#105]
shula

**Comment by shulammiteofua** [comment]
[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/How%20it%20works.png](url) This is a part of the documentation for users that onboard them to the website.

**Comment by teenuade** [comment]
https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/pull/90

Link for the documentation process, including both the designers and developers stages
