### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#106]

**Comment by NwokoDaniel** [comment]
Done with the Contact Us page.
Link below:

https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/pull/62/commits/0ee4fd678feb4a9721da3781ce8fb59db84aa37b#diff-5f6fa2d58ae5c2643b83fc6f49c350955a2cecccfd6e02b2220d3771003388a0
