### ISSUE TITLE
Contact Us Drop Down Screen

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#107]

**Comment by NwokoDaniel** [comment]
Designed the Contact Us drop down screen for Bytsfy.
Link below:

https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/pull/62/commits/0ee4fd678feb4a9721da3781ce8fb59db84aa37b#diff-3eeb710f1b614eb2aef7d5cab5da4b7f47e2898b9dde3d8c140e21ee6945d0d2
