### ISSUE TITLE
User Flow

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#117]

**Comment by belrah** [comment]
combined work

**Comment by Enkqaay** [comment]
This is the link to the userflow diagram

[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/User%20Flow%20Diagram.png](url)

**Comment by teenuade** [comment]
https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/pull/83/commits/76d75c2871ec209267c2dc1d6fe7f47d42e4c0fe
The user flow, three people worked on this section
