### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#162]

**Comment by juliusogunsola** [comment]
[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/Main%20Resource%20Page.png](url)

This is the link to the main resources page.

[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/JSON%20Data%20structure.png](url)

[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/CSV%20or%20JSON%20for%20data%20storage](url)

[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/Combine%20JSON%20to%20CSV%20with%20python.png](url)

[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/Flatten%20JSON%20Data%20using%20Pandas.png](url)

[https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/blob/main/Design-Screens/Desktop-View/Comparing%20CSV%20and%20JSON%20files.png](url)

These are the links to each resource screen design.
