### ISSUE TITLE
Daniel Nwoko

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#189]

**Comment by NwokoDaniel** [comment]
Link for User Flow PDF format: https://github.com/NwokoDaniel/Chunk_file_team_46_Bytsfy/blob/d9442688b30ec423a65e4c14b11c7af56d2b88d3/Design-Screens/Desktop-View/User%20Flow.pdf

Link for User Flow png format: https://github.com/zuri-training/Chunk_file_team_46_Bytsfy/pull/195/commits/0d2b6868b6240d6f34be7b477ee6738b250bf584

(I and two other designers worked on the User Flow)
