### ISSUE TITLE
Save File Page

### ISSUE THREAD

**Issue by belrah** [zuri-training/Chunk_file_team_46_Bytsfy#99]
Obed

**Comment by Obed-israel** [comment]
<img width="1448" alt="SAVED FILES PAGE" src="https://user-images.githubusercontent.com/99468398/183787121-9a569946-1415-4233-b82a-35a443cb8f53.png">

<img width="414" alt="SAVED FILES PAGE MOBILE" src="https://user-images.githubusercontent.com/99468398/183787177-c55442e0-5f46-4e23-86cb-943f08e75c56.png">

**Comment by Obed-israel** [comment]
This contain both the desktop view and mobile view  of the saved files page
